### PR TITLE
New treatment assignment methods, refactor, cleanup

### PR DESCRIPTION
**Pull request by RoyalTS**
This

- implements both the "global" and "stratum" methods for handling misfits in treatment assignment
- tests behavior of the entire function more thoroughly: We now test not only overall treatment assignment proportion but also within-stratum behavior
- cleans everything up a bunch

### CODE REVIEW

**Comment by RoyalTS** [comment]
Also fixes #8 :)

**Comment by manmartgarc** [comment]
@redouane-dziri  Could you please quickly format the changes to conform with [PEP-8](https://www.python.org/dev/peps/pep-0008) convention?

**Comment by RoyalTS** [comment]
Haha, you're about to kick off a religious war. Which _parts_ of PEP8? Got a favorite linter?

**Comment by manmartgarc** [comment]
> Haha, you're about to kick off a religious war. Which _parts_ of PEP8? Got a favorite linter?

Oh boy! I do not have time for a part-time crusade. Just the maximum line length. Specially for the doc-strings.

**Comment by RoyalTS** [comment]
79 chars?

**Comment by manmartgarc** [comment]
Yes!

**Comment by RoyalTS** [comment]
Et voila!

**Pull request merged**
